### ISSUE TITLE
Que tal usar datasets-br?

### ISSUE THREAD

**Issue by ppKrauss** [nfephp-org/sped-common#114]
Para a [lista de códigos das UFs, *UFlist*](https://github.com/nfephp-org/sped-common/blob/master/docs/UFList.md)... É apenas um exemplo de aplicação, são previstos outros *datasets*, a exemplo do [Data Packaged Core Datasets](https://github.com/datasets). 

* lista das abreviações  de UF: https://github.com/datasets-br/state-codes
* [visualização do descritor JSON do dataset](http://data.okfn.org/tools/view?url=https%3A%2F%2Fraw.githubusercontent.com%2Fdatasets-br%2Fstate-codes%2Fmaster%2Fdatapackage.json)

**Comment by robmachado** [comment]
Na verdade existem outros como https://github.com/brazanation/php-states, que eu pretendo incrementar e usar no lugar desses que vocês listou no inicio da mensagem. Devo incluir no repositório do brazanation coisas como (uri dos autorizadores de NFe, CTe, MDFe), entre outras informações necessárias na implementação do projeto SPED.

**Comment by ppKrauss** [comment]
Olá @robmachado , gostei desse *php-states*. Influi o fuso horário no CSV e fiz um algoritmo gerador das classes, dê uma olhada em https://github.com/brazanation/php-states/issues/3#issuecomment-301367853

**Comment by robmachado** [comment]
Tem outras informações sobre os estados relativos a NFe por exemplo, veja aqui https://github.com/nfephp-org/sped-nfe/blob/v5.0/storage/wsnfe_3.10_mod55.xml

**Comment by ppKrauss** [comment]
@robmachado , ok, acho que vou tentar colaborar... Mas começando bem pelo começo, ainda terei muito chão antes de chegar no XML ;-)

Voltando aos estados, parace que não sou o primeiro a [argumentar pela demanda de *datasets*](https://github.com/brazanation/php-states/issues/3). De fato, os dados já existem em [datasets-br/state-codes](https://github.com/datasets-br/state-codes), e são totalmente auditáveis e padronizados... Então fica muito mais simples ter o "código PHP gerado pelos dados". 

Tive dificuldades com o validador de estilo do PHPMD (na redação uso Atem e estaria em ordem), então não enviei ainda o gerador (meu `geraClasses.php`), mas as correções produzidas por ele: estão [neste pull-request](https://github.com/brazanation/php-states/pull/7)... está tudo certo até aqui?
