### ISSUE TITLE
BUG certificado sendo removido mesmo em operações concorrentes

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-common#117]
A Classe SOAP requer os certificados em arquivo para usar, a SoapBase::class cria esses arquivos de forma temporária e depois os remove. Mas quando existem operações concorrentes com o mesmo certificado (mesmo CNPJ) pode ocorrer de uma operação remover os certificados que seriam usados em outra.

**Comment by tavinus** [comment]
Olá, eu estava debugando outro problema e notei que na real vocês estão recriando os certificados toda vez que tem uma chamada pro web-service com a função send().

Ou seja, se mantiver o objeto `Tools` e fizer mais de uma chamada `send()` os certificados serão recriados e os antigos ficarão na pasta tmp sem uso e sem deletar.

A solução que eu encontrei foi mover a chamada `$this->saveTemporarilyKeyFiles()` para o construtor da classe SoapCurl e remover do método `send()`. Assim conseguimos manter e reutilizar os certificados e também todos os certs usados serão excluídos ao final da execução (antes só excluia os certs da última chamada).

Mais infos na minha resposta da outra issue citada acima:
https://github.com/nfephp-org/sped-common/issues/141#issuecomment-348343192

**Comment by lpj145** [comment]
@robmachado como vai meu amigo, boa noite, finalmente terminei a base para um desenvolvimento mais saudavél desse sistemas fiscais. Queria saber se isso foi resolvido, e se não, achei uma pesquisa na internet implementada com C para não precisar mais criar arquivo, e fazer a leitura do certificado a partir da memória, como anda as coisas? saúde da familía vai bem ? Abraços...

**Comment by robmachado** [comment]
@tavinus Obrigado realmente e solução é a mais indicada. Vamos promover essa melhoria !

**Comment by robmachado** [comment]
Marcos;

Por ora ainda não é possível usar os certificados apenas em memória. Não
encontrei uma implementação passível de ser usada em larga escala.
Quanto a saúde estive e estarei mais lento pois estou com calculos renais
que estão causando um grade problema, mas já já passa.

Abraço

**Comment by lpj145** [comment]
Fico feliz que se encontra, e triste pelo problema, minha familía é pobre, mas herdamos essa triste herança do calculo renal kkk ... gostaria de te falar que encontrei uma saída no próprio php na extensão do curl, porém que ainda não foi implementada, se puder, da uma olhadinha no gitter depois, fiz vários comentários sobre lá no grupo do sped-common, o que acha de criarmos um grupo no telegram ? é uma plataforma muito dinamica, e coisas mais urgentes podemos tratar melhor do assunto.

**Comment by lpj145** [comment]
https://t.me/joinchat/GE_IWhFZh3ufRIBGKahaog aqui o grupo do telegram
