### ISSUE TITLE
ErrorException: Undefined index: organizationalUnitName

### ISSUE THREAD

**Issue by tiagocardosos** [nfephp-org/sped-common#132]
Na maioria dos casos o campo organizationalUnitName existe, porém encontramos um caso que a informação é inexistente.

Certificado empresa A:
<img width="718" alt="screen shot 2017-09-26 at 08 58 28" src="https://user-images.githubusercontent.com/1429801/30859204-043186f6-a299-11e7-92fd-5bfa9fabb3fc.png">

Certificado empresa B:
<img width="709" alt="screen shot 2017-09-26 at 08 59 02" src="https://user-images.githubusercontent.com/1429801/30859205-0456e7e8-a299-11e7-93d4-76e702677b2e.png">

```Arquivo:
../nfephp-org/sped-common/src/Certificate/PublicKey.php:98
```

**Comment by robmachado** [comment]
uhhmmm ! Não deveria ocorrer o erro pois é verificado ISSET antes de tentar obter essa propriedade do certificado. ?!?!  Talvez seja necessário mudar essa verificação para por exemplo !empty().
Tiago, você poderia fazer um teste alterando a linha:
de
if (isset($detail['issuer']['organizationalUnitName'])) {
    $this->cspName = $detail['issuer']['organizationalUnitName'];
}

Para

if (!empty($detail['issuer']['organizationalUnitName'])) {
    $this->cspName = $detail['issuer']['organizationalUnitName'];
}
 
E ver se o erro desaparece !

**Comment by tiagocardosos** [comment]
@robmachado, já verificamos aqui! O erro foi nosso, estávamos com a versão desatualizada e não tinha o ```isset```.
