### ISSUE TITLE
getDistDFe

### ISSUE THREAD

**Issue by cbragato** [nfephp-org/sped-common#164]
Eu li um _Issue_ na NFEPHP (atualmente depreciada, que havia esta função, a qual não estou conseguindo encontrar) https://github.com/nfephp-org/nfephp/issues/214. 
Gostaria de saber se já há algo semelhante desenvolvido nas bibliotecas atuais. E se não ha ainda, como eu poderia utilizar a função da biblioteca anterior, ou até ajudar a transportar esta função para as novas bibliotecas. Agradeço imensamente a ajuda.

**Comment by robmachado** [comment]
https://github.com/nfephp-org/sped-nfe/blob/master/docs/metodos/DistDFe.md
