### ISSUE TITLE
SoapBase::setTemporaryFolder faz a chamada do SoapBase::saveTemporarilyKeyFiles

### ISSUE THREAD

**Issue by MarcosSSJunior** [nfephp-org/sped-common#173]
No construtor da classe SoapBase é realizado a chamada do SoapBase::setTemporaryFolder, onde é chamado o SoapBase::saveTemporarilyKeyFiles criando os temporários, e logo após é chamado SoapBase::saveTemporarilyKeyFiles novamente. Isso tem real necessidade? Pois SoapBase::removeTemporarilyFiles vai remover apenas os últimos.

No construtor:
https://github.com/nfephp-org/sped-common/blob/f462c7d684f713bc06feaf620787dda57589b386/src/Soap/SoapBase.php#L157-L161

No SoapBase::setTemporaryFolder:
https://github.com/nfephp-org/sped-common/blob/f462c7d684f713bc06feaf620787dda57589b386/src/Soap/SoapBase.php#L252-L254

**Comment by robmachado** [comment]
@MarcosSSJunior  Sim Marcos você está certo esse processo deve ser revisado e refatorado para evitar essa duplicidade. Vamos trabalhar nisso !

**Comment by robmachado** [comment]
Corrigido o comportamento
