### ISSUE TITLE
Erro de permissões em ambiente compartilhado

### ISSUE THREAD

**Issue by gersonfs** [nfephp-org/sped-common#176]
Olá

Estou usando este projeto em alguns clientes num servidor de hospedagem compartilhada com CPanel.  Quando ativei o sistema no 2º cliente, tive problemas de permissão nesta parte: 
https://github.com/nfephp-org/sped-common/blob/7a89e628f98ccd0a692000180963f091f0afa3a2/src/Soap/SoapBase.php#L157

A pasta ``sys_get_temp_dir() . '/sped/'`` só tem permissão de escrita para o usuário que criou ela, logo meu segundo usuário linux não consegue criar subpastas dentro dela. Teria como mudar a permissão dessa pasta sped para 777 e as demais manter a permissão atual? Acho que não tem problema, pois para cada cnpj há uma sub-pasta no caso do projeto sped-nfe.

Ou então permitir definir o local dessa pasta via arquivo de configuração ou algum setter.

**Comment by gersonfs** [comment]
Se me permitir, crio um pull request onde defino um método que retorna ``sys_get_temp_dir() . '/sped/'`` por padrão, ou um valor personalizado definido no arquivo config.json

**Comment by robmachado** [comment]
Fiz algumas melhorias no codigo das Classes SOAP, então para mudar o local dos arquivos temporários pode fazer assim

$tools = new Tools($json, $certificate);
$tools->soap->setTemporaryFolder('/meu/local/secreto/');

Isso já deve facilitar seu trabalho ai

**Comment by gersonfs** [comment]
Olá Roberto

Para mim atende perfeitamente dessa forma. Mas você não acha que esse problema pode ser recorrente para outros usuários? Seria bom a biblioteca tratar isso de forma automática, poderia criar uma pasta “sped-uidusuario” ou “sped-cnpj”. Pois acho que isso pode ocorrer com outros desenvolvedores e dar uma certa demanda de suporte no fórum sped-nfe.

Obrigado!

**Comment by robmachado** [comment]
Você não olhou direito a pasta. A API já cria isso 
/tmp/sped/<CNPJ>/certs

ou se você definir outra pasta

/meu/diretorio/secreto/<CNPJ>/certs

Roberto

**Comment by gersonfs** [comment]
Sim, isso eu entendi, como falei para mim serve dessa forma, com o método para alterar a pasta. Estou me referindo a outros desenvolvedores de sistema que vão ter o mesmo problema que eu, eles vão ter que se ligar de chamar esse método para alterar o caminho da pasta. Foi por isso que me referi a API já tratar isso de forma nativa.
