### ISSUE TITLE
Sugestão: Casos de testes de unidade extras para a função Signer::sign.

### ISSUE THREAD

**Issue by zoiosilva** [nfephp-org/sped-common#184]
Inspirado pela discussão iniciada no PR #181, talvez seria bom termos casos de teste de unidade testando a assinatura digital de documentos com estruturas diferentes. Assim, quando alguém tiver a inspiração de fazer uma melhoria no método `Sign`, ficaria mais seguro de não estar quebrando o uso nos outros componentes.

**Comment by lpj145** [comment]
na verdade, o interessante, é que cada documento, que implementasse sua ou uma interface Sped tivesse algo como getSignNode ou signedNode coisa do tipo, onde devolveria  o nó a ser assinado, podendo ser um ou mais, Sign não deve saber o que esta tentando assinar, ele só deveria pegar essa node, elemento, texto e tentar assinar, no repositorio sign, teríamos um wrapp com strategy pattern, onde TextSign, XmlSign fossem os ideais para essas assinaturas.

**Comment by robmachado** [comment]
Srs. A classe Signer é e deve ser o mais GENÉRICA possível !
Os projetos que fazem uso dessa classe é que devem passar os parâmetros corretos para que a assinatura seja feita corretamente. É dentro desses projetos específicos onde são definidos nos nodes a serem assinados e outros parâmetros construtivos.

**Comment by zoiosilva** [comment]
Correto, concordo. Acrescento ainda que os testes podem funcionar como uma documentação viva do projeto, testando comportamentos que devem obrigatoriamente ser atendidos para que não quebre projetos dependentes.

**Comment by robmachado** [comment]
O nivel de cobertura por testes unitários ainda está baixo em vários projetos. Alguns (mais simples) já estão com uma cobertura melhor. Os testes unitários são muito importantes para evitar a QUEBRA de padrões e de funcionalidade. E com eles fica mais difícil acontecerem falhas quando alguém faz uma alteração imprópria.
