### ISSUE TITLE
Problema: Validação confusa

### ISSUE THREAD

**Issue by lpj145** [nfephp-org/sped-common#191]
https://github.com/nfephp-org/sped-common/blob/1d0bb62b3599f6ae156426ead4497392c2c9fb05/src/Validator.php#L30

Há algum meio de retornar esse resultado menos confuso, sinto que em relação a validação anterior esse modo ta meio complexo e confuso pra resolver, só consegui resolver os erros do xml com outro validador o da tecnhospeed.

**Comment by robmachado** [comment]
O problema maior é gerar uma TRADUÇÃO do ingles se é a isso que você se refere!

**Comment by lpj145** [comment]
eu me refiro as nomenclaturas dos erros, que por exemplo, não me dizem exatamente onde é o problema, tipo no nó tal tem x error.

**Comment by robmachado** [comment]
Isso infelizmente não é possivel !!! Usando o XSD para fazer essa validação.
A validação com o XSD retorna dados de sua própria maneira. E valida apenas a estrutura estabelecida.
Em outros projetos como o sped-efdrestul, sped-efinanceira, sped-esocial, eu peguei o XSD e criei JsonSchemas que faz uma PRE validação nos dados passados, E esse JsonSchema retorna informações mais especificas que o o retorno do XSD.
