### ISSUE TITLE
Digest Value não corresponde ao conteúdo

### ISSUE THREAD

**Issue by langaro** [nfephp-org/sped-common#202]
Boa tarde gente.
Primeiramente muito obrigado pelas classes, realmente estão me ajudando muito.
Estou com um problema na assinatura do XML da NFSe. Estou tendo o seguinte retorno:

> (
    [mEnvioLoteRPSSincronoResult] => <?xml version="1.0" encoding="utf-8"?><EnviarLoteRpsSincronoResposta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.abrasf.org.br/nfse.xsd"><DataRecebimento>0001-01-01T00:00:00</DataRecebimento><ListaMensagemRetorno><MensagemRetorno><Codigo>E0800</Codigo><Mensagem>Erro na geração da assinatura!
Assinatura inválida. A Assinatura da nota não confere com a informação contida no XML.</Mensagem><Correcao>Verifique as informações do seu Certificado Digital</Correcao></MensagemRetorno></ListaMensagemRetorno></EnviarLoteRpsSincronoResposta>
)

A função Signer::isSigned retorna o seguinte:

> The XML content does not match the Digest Value. Probably modified after it was signed

Ainda estou realizando testes, então o código está provisório, mas estou fazendo o seguinte:

`
function AssinarXML_GerarXMLAssinado() {
    $xml = file_get_contents("caminho do xml assinavel");

    $tagname = 'InfDeclaracaoPrestacaoServico';
    
    $mark = 'Id'; 
    
    $algorithm = OPENSSL_ALGO_SHA1; 
    
    $canonical = [true,false,null,null]; 

    $rootname = 'tcDeclaracaoPrestacaoServico';

    try {
        
        $pfx = file_get_contents('caminho do certificado .pfx');
        $certificate = Certificate::readPfx($pfx, 'senha do certificado .pfx');

        $signed = Signer::sign(
            $certificate,
            $xml,
            $tagname,
            $mark,
            $algorithm,
            $canonical,
            $rootname
        );

        $arquivoXMLFinal = fopen("caminho para gravar um xml com a string assinada", "w") or die("Erro ao gravar XML!");
        fwrite($arquivoXMLFinal, $signed);        
        fclose($arquivoXMLFinal);

    } catch (\Exception $e) {
        //aqui você trata a exceção
        echo $e->getMessage();
    }
    
}
`

Será que o problema é porque eu estou gravando o XML assinado em um arquivo? Será que preciso assinar direto o XML? Se for isso, tem como fazer isso nessa biblioteca?

Ressalto que a estrutura da assinatura está totalmente correta conforme o modelo da prefeitura, tem Reference ID e tudo mais.

Muito obrigado desde já e parabéns pela biblioteca, muito útil!

**Comment by robmachado** [comment]
@langaro 
A coisa é um pouco mais complicada que isso. O digest depende de outros fatores como por exemplo se o xml está ou não formatado. 
Para as NFSe é sempre muito mais complicado, pois a documentação é RIDICULA, e as informações não são CORRETAS muitas vezes. 
Minha recomendação, é obter um XML VALIDO e tentar reproduzir o DIGEST desse XML, o que pode ser uma tarefa TEDIOSA e meticulosa, para entender o que está ocorrendo.
Outra sugestão é tentar usar o pacote do [GITHUB robrichards/xmlseclibs](https://github.com/robrichards/xmlseclibs) que é mais genérico que esse que eu uso.

**Comment by robmachado** [comment]
Apenas a titulo de exemplo, esse pacote está sendo usado aqui 

[sped-nfse-ipm](https://github.com/nfephp-org/sped-nfse-ipm/blob/master/src/Common/Signer.php)

**Comment by langaro** [comment]
@robmachado entendo. Realmente a documentação é pífia. Eu fiz algumas tentativas usa do a robrichards/xmlseclibs mas não tive sucesso em inserir o reference URI na tag. Enfim, obrigado. Farei mais tentativas e informo aqui. Obrigado!

**Comment by robmachado** [comment]
Qual é o modelo que você quer implementar ?? para qual municipio ??

**Comment by langaro** [comment]
@robmachado Município de Tapejara/RS, a documentação está em http://homologatapejara.nfse-tecnos.com.br.

**Comment by robmachado** [comment]
Se você tiver interesse posso desenvolver uma API para a tecnos. mas necessito alguma ajuda $$

**Comment by langaro** [comment]
Obrigado pela disponibilidade, mas vou tentar mais por aqui. Entro em contato!

**Comment by marcoskubas** [comment]
Olá @langaro , tudo bem? O Tópico está fechado mas não tem uma solução, conseguiu resolver de alguma forma? Estou passando pelo mesmo com a prefeitura de Flores da Cunha/RS no sistema de Tecnos.
