### ISSUE TITLE
Certificado Transmissor sem CNPJ

### ISSUE THREAD

**Issue by elvispdosreis** [nfephp-org/sped-common#207]
Pessoa desculpe me postar uma pergunta aqui que não se reference a nota eletrônica, mais eu estou a vários dias sem solução, gostaria da ajuda de voces.

Eu preciso comunicar a um serviço da receita *https://sisobrapref.receita.economia.gov.br/sisobraprefWS/recepcao?wsdl* porem ele exige uma criptografia na comunicação com a transferência da informação do CNPJ "OID: 2.16.76.1.3.3"

Porem todas as forma que que tente sempre tenho a mesma resposta **Certificado Transmissor sem CNPJ**

eu já tentei a forma do soap nativo do php `SoapClient` e também as classe `SoapCurl` e `SoapNative` do projeto *nfephp-org/sped-common*

O comando me retorna o CNPJ no certificado corretamente
`$certificado->getCnpj();`

se alguém puder me dar um norte eu agradeço muito.

**Comment by robmachado** [comment]
Não faço a menor ideia do que seja esse serviço !
A comunicação SOAP e o próprio WSDL por você indicado não trazem nenhuma informação a respeito de CRIPTOGRAFIA!!
Isso pode estar a documentação do projeto (que eu desconheço), porém a mensagem de retorno está bem clara **Certificado Transmissor sem CNPJ**.
Isso ocorre pois provavelmente você está usando um certificado e-CPF e não um e-CNPJ conforme solicitado.

**Comment by robmachado** [comment]
Repito !!! não vi, não li e desconheço totalmente a documentação do projetos e suas exigências de estrutura.

**Comment by elvispdosreis** [comment]
Roberto, desculpe.
A principio eu tbm desconfiei do certificado, porem eu consigo logar normalmente no e-CAC https://cav.receita.fazenda.gov.br/autenticacao/login

Manual
http://receita.economia.gov.br/orientacao/tributaria/declaracoes-e-demonstrativos/sisobrapref-sistema-de-cadastro-de-obra-modulo-prefeitura/arquivos/manual-web-service-sisobrapref-26022019.pdf/view

**Comment by robmachado** [comment]
Eu li a documentação e nos erros o que ele indica é exatamente isso "QUE NÃO é UM e-CNPJ".

Mas você tem certeza que está usando o mesmo certificado tanto para assinar como para transmitir ??

Pela instalação do certificado no browser é possível ver algumas informações mas esse OID não, a função mencionada ($cert->getCNPJ()), faz exatamente isso pega o OID 2.16.76.1.3.3 de dentro do certificado digital, então se tem retorno dessa função o certificado testado pela classe é um e-CNPJ. 

Outro motivo de falha pode ser o próprio webservice retornando um ERRO incorreto ! E se for esse caso somente entrando em contato com a equipe técnica responsável.
