### ISSUE TITLE
Possibilidade de Assinar uma Tag dentro de outra com o mesmo Nome

### ISSUE THREAD

**Issue by ramonvic** [nfephp-org/sped-common#222]
Estou usando essa biblioteca como base para integração com a Prefeitura de Goiania ( por mas que tenha outra já com esse intuito ).

Porém a validação do Request para Goiania é feito na Tag **`Rps`** dentro da tag **`InfDeclaracaoPrestacaoServico`** 

Sendo o Path para o nó a ser assinado: **`Rps -> InfDeclaracaoPrestacaoServico -> Rps`**

O Método `Signer::sign` aceita um parâmetro `tagname`, porém não consegui fazer ele selecionar a tag correta.

Há a possibilidade de mudar a visibilidade desses métodos para protected para poder ser sobreescritos?

**Comment by robmachado** [comment]
https://github.com/nfephp-org/sped-nfse-amtec
