### ISSUE TITLE
SoapInterface sem o método público httpVersion

### ISSUE THREAD

**Issue by rodolfojnn** [nfephp-org/sped-common#225]
Bom dia! Em uma implementação, precisei forçar o http version para 1.1:

`$nfeTools->soap->httpVersion('1.1');`

Mas o método não existe na SoapInterface, apenas na classe SoapBase (que implementa a SoapInterface). Fiquei na dúvida se estou fazendo algo errado, ou se o método realmente está faltando na interface.

**Comment by afbarboza94** [comment]
O codigo:
$this->soap = new SoapCurl($this->certificate);
Foi removido da __construct de NFePHP\NFe\Common\Tools

A solução que encontrei foi instanciar a SoapCurl junto com a Tools e passar a instancia da primeira para a segunda, respectivamente.
Ficou mais ou menos assim:

use NFePHP\Common\Soap\SoapCurl;

$soap = new SoapCurl($cert);
$soap->httpVersion('1.1');

$nfeTools->loadSoapClass($soap);

Espero que funcione.
