### ISSUE TITLE
Falha ao assinar xml nfse campinas

### ISSUE THREAD

**Issue by DanielBASouza** [nfephp-org/sped-common#233]
Eu estou com um problema, na hora de assinar um xml, ele monta e assina certinho o documento mas quando tento enviar fala que está com erro na assinatura, fui verificar a assinatura e retorna o seguinte erro.

_Reference 1 digest is invalid because the computed digest differs from the digest in the XML._

**Comment by robmachado** [comment]
A classe Signer está sendo usada por MILHARES de aplicativos eu mesmo uso centenas de vezes ao dia, então o erro não está na assinatura.
Você está enviando O QUE ?? NFe, NFCe, CTe, CTeOS, MDFe ??

**Comment by DanielBASouza** [comment]
Sim sim, eu sei que ela é altamente utilizada por isso mesmo recorri a ela, acredito que seja alguma cagada que eu esteja fazendo, estou tentando enviar uma NFSe(Campinas).

**Comment by robmachado** [comment]
Pois é as NFSe em sua grande maioria vão requerer estruturas com ajustes grandes ou pequenos, especialmente na assinatura digital. 
Eu tive de criar ou alterar vários pacotes e ajusta-los especificamente para cada provedor de nfse que já desenvolvi.
Seja na criação de xml, na comunicação SOAP e sempre na assinatura digital.
Resumindo não dá para usar o método Signer desse pacote diretamente.
