### ISSUE TITLE
Erro em quebra de linha na tag informação complementar (infCpl) após upgrade para versão v5.0.48

### ISSUE THREAD

**Issue by fcristinadebora** [nfephp-org/sped-common#238]
Ao emitir uma NF-e, na tag `<infCpl>` as quebras de linha que antes eram convertidas para a tag `<br />` agora estão sendo salvas como `< br/>`, ao imprimir o DANFE diretamente a partir do conteúdo do XML, as quebras de linha acabam não funcionando. 

Fiz o downgrade do package para a versão anterior: v5.0.47 e funciona normalmente, o problema está de fato na versão v5.0.48. É um problema de fato, ou foi feito propositalmente?

Exemplo do problema na versão 5.0.48: 
![image](https://user-images.githubusercontent.com/17615066/102398177-b308cf80-3fbd-11eb-913b-518ec34f8807.png)

Exemplo do comportamento na versão 5.0.47
![image](https://user-images.githubusercontent.com/17615066/102398279-d7fd4280-3fbd-11eb-800c-5abea20d58e2.png)

**Comment by robmachado** [comment]
Alguns problemas ocorrem em algumas situações especificas, ao inserir caracteres INACEITÁVEIS como o & ou < ou > além de aspas e apostrofes.
Para fazer a quebra de linha eu sugiro você usar por exemplo marcações com ; ou | ou : ou ainda :: e ao renderizar isso no seu sistema faça a conversão adequada. Infelizmente são muitas possibilidades dos usuários (e mesmo as softhouses) não obedecerem certos padrões nem fazer as limpezas adequadas  nas strings e fica muito difícil, prever a "CACA" que pode ser feita. 
Vou ver se dá para reverter essa alteração sem causar mais problemas.
Mas minha sugestão é não inserir ou permitir caracteres que não são inaceitáveis, ou seja evite usar &, < , > , ', " e qualquer carácter de controle ou símbolos.

**Comment by fcristinadebora** [comment]
Entendi! Obrigada pelo retorno :)
