### ISSUE TITLE
Suporte League/Flysystem 2.0

### ISSUE THREAD

**Issue by elvispdosreis** [nfephp-org/sped-common#239]
Por favor poderia adicionar suporte ao league/flysystem 2.0

**Comment by robmachado** [comment]
São muitas alterações a serem feitas no momento terá de esperar, vários outros pacotes são dependentes disso.
Possivelmente irei RETIRAR o flysystem desse pacote ! e usar apenas os comandos  do próprio php.

**Comment by robmachado** [comment]
Eu removi a dependência do flysystem desse pacote.
Por favor teste ai !

**Comment by elvispdosreis** [comment]
Problem 1
    - nfephp-org/sped-common[v5.0.35, ..., v5.0.51] require league/flysystem ^1.0 -> found league/flysystem[1.0.0, ..., 1.1.4] but it conflicts with your root composer.json require (^2
.0).
    - nfephp-org/sped-da v1.0.0 requires nfephp-org/sped-common ^5.0 -> satisfiable by nfephp-org/sped-common[v5.0.35, ..., v5.0.51].
    - Root composer.json requires nfephp-org/sped-da ^v1.0.0 -> satisfiable by nfephp-org/sped-da[v1.0.0].
