### ISSUE TITLE
OpenSSL 3

### ISSUE THREAD

**Issue by RicLzPt** [nfephp-org/sped-common#279]
Prezados, estou no ubuntu 22.04 que está com o novo OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022) (até então era o 1.1.1). Meu PHP:
PHP 8.1.5 (cli) (built: Apr 21 2022 10:32:13) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.5, Copyright (c), by Zend Technologies
    with Xdebug v3.1.4, Copyright (c) 2002-2022, by Derick Rethans

Ao tentar assinar uma nfe tenho o erro PHP Fatal error:  Uncaught NFePHP\Common\Exception\CertificateException: Impossivel ler o certificado, ocorreu o seguinte erro: (error:0308010C:digital envelope routines::unsupported)

Este erro não ocorre na versão 1.1.1 do OpenSSL.
Alguém mais passando por isso?

**Comment by robmachado** [comment]
Os algorítimos do OPENSSL versão 3 são mais atualizados que os usados na assinatura da NFe
Para permitir o uso do "provider legacy" do OpenSSSL
Deve algo como:
[legacy_sect]
   activate = 1
Dentro do openssl.conf

**Comment by robmachado** [comment]
Isso é causado por certificados usando rotinas de encriptação mais fracas não mais suportadas pelo OpenSSL v3

**Comment by RicLzPt** [comment]
Muito obrigado, @robmachado 

Pesquisando no site do projeto openSSL vi que para ativar o legado da versão 1.1.1 devemos:
- adicionar na chave [provider_sect] o conteúdo legacy = legacy_sect
- abrir uma nova chave [legacy_sect] e adicionar activate = 1
- descomentar o activate = 1 da chave [default_sect]
tudo funcionando. Ficou assim para alguém que possa ter o mesmo problema.

/etc/ssl/openssl.cnf
`# List of providers to load
[provider_sect]
default = default_sect
legacy = legacy_sect
# The fips section name should match the section name inside the
# included fipsmodule.cnf.
# fips = fips_sect

# If no providers are activated explicitly, the default one is activated implicitly.
# See man 7 OSSL_PROVIDER-default for more details.
#
# If you add a section explicitly activating any other provider(s), you most
# probably need to explicitly activate the default provider, otherwise it
# becomes unavailable in openssl.  As a consequence applications depending on
# OpenSSL may not work correctly which could lead to significant system
# problems including inability to remotely access the system.
[default_sect]
activate = 1

[legacy_sect]
activate = 1`

**Comment by robmachado** [comment]
Fico feliz em saber que resolveu o problema

**Comment by sicoksoftware** [comment]
Estava enfrentado esse problema com certificados de algumas certificadores, mais segui os passos deu certo valeu. abraço

**Comment by fernandorl** [comment]
Alguém conseguiu fazer no XAMPP com Windows?

**Comment by robmachado** [comment]
Este issuer está fechado!! pergunte no grupo do google

**Comment by eduardomrj** [comment]
> legacy_sect



> Muito obrigado, @robmachado
> 
> Pesquisando no site do projeto openSSL vi que para ativar o legado da versão 1.1.1 devemos:
> 
> * adicionar na chave [provider_sect] o conteúdo legacy = legacy_sect
> * abrir uma nova chave [legacy_sect] e adicionar activate = 1
> * descomentar o activate = 1 da chave [default_sect]
>   tudo funcionando. Ficou assim para alguém que possa ter o mesmo problema.
> 
> /etc/ssl/openssl.cnf
> 
> [provider_sect] default = default_sect legacy = legacy_sect
> 
> [default_sect] activate = 1
> 
> [legacy_sect] activate = 1

Fiz essa modificação e não funcionou.
Ambiente:
Linux ubuntu 24
Php 8.2
Diferença que está em docker mas as configurações do SSL foram aplicadas no arquivo.

Mais alguma ideia? Grato

**Comment by eduardomrj** [comment]
Talvez alguém passe pelo problema, a resposta do colega @robmachado está correta, mas faltou um detalhe.

[openssl_init]
providers = provider_sect   ## faltou essa linha

[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1

**Comment by reistr85** [comment]
Fiz o que recomendaram e deu certo.
