### ISSUE TITLE
Dúvida: É possível usar a classe para assinar documentos txt?

### ISSUE THREAD

**Issue by luispiressaipos** [nfephp-org/sped-common#286]
Boa tarde,
Estou desenvolvendo uma rotina para exportação de um arquivo TXT para o estado de Santa Catarina.
De acordo com o manual, esse arquivo deve ser assinado usando o certificado do PAF.

Já utilizamos essa classe no sistema para fazer a assinatura de documentos XML das notas, mas não encontrei uma forma de faze-lo em arquivos texto.

É possível?

**Comment by robmachado** [comment]
**Não !!**  Cada formato de documento tem uma estrutura de assinatura diferente.
Deve ser escrita uma rotina especifica para assinar esse que você deseja.

**Comment by luispiressaipos** [comment]
Muito obrigado pelo retorno Roberto!
Vou seguir a implementação sem a classe então.

Abraço!
