### ISSUE TITLE
É possível criar múltiplas assinaturas num unico Documento XML?

### ISSUE THREAD

**Issue by SedaxGaming** [nfephp-org/sped-common#304]
Olá pessoal! Isso é mais uma duvida do que uma issue, mas vi que tem a tag com help wanted, resolvi abrir.

Não encontrei no código um método que crie múltiplas assinaturas, e quando tento utilizar o Signer:sign() pela segunda vez, ele acaba removendo a assinatura anterior.
Estou utilizando o projeto para montar NFS-e, e no momento a que necessita de duas assinaturas é a cidade de Porto Alegre - RS.
Existe algum método? Grato desde já

**Comment by robmachado** [comment]
Não o sped-common não foi feito para isso, ele está feito apenas para NFe/NFCe/CTe/CTeOS/MDFe/BPe

Não está apto a realizar assinaturas em NFSes !! e nunca estará, pois não é foco deste projeto.
