### ISSUE TITLE
definindo responsabilidade do certificado

### ISSUE THREAD

**Issue by tonicospinelli** [nfephp-org/sped-common#41]
certificado deve ser um **value object** que deverá conter as seguintes propriedades:

* **companyName**: _string_ nome da empresa
* **companyIdentifier**: _string_ cnpj da empresa
* **privateKey**: _string_ chave privada PEM
* **publicKey**: _string_ chave pública PEM
* **certificate**: _string_ certificado PEM (chave publica + cadeia )
* **caInfo**: _string_ caminho absoluto para cacerts do sistema operacional
* **validFrom**: _\DateTime_ data de início da validade do certificado
* **validTo**: _\DateTime_ data de término da validade do certificado

os comportamentos esperados:
* **encrypt($text, $algorithm)**: _string_ fará a criptografia baseada em um [algoritmo](http://us3.php.net/manual/en/openssl.signature-algos.php)
* **isExpired()**: _bool_ verifica de a data atual está dentro do período de validade do certificado

_EDIT:_ 
* alterado nome de `sign` para `encrypt`
* novas propriedades adicionadas `certificate`, `companyIdentifier`

**Comment by robmachado** [comment]
O certificado seria passado como na construção ou por um método

**Comment by tonicospinelli** [comment]
por ser um objeto de valor, ele deve receber todas as propriedades no construtor:

```php
public function __construct(
    $companyName,
    $privateKey,
    $publicKey,
    $caInfo,
    \DateTime $validFrom,
    \DateTime $validTo
)
```

**Comment by tonicospinelli** [comment]
quem deve ler o arquivo é outra classe e depois preencher essas propriedades 😉

**Comment by robmachado** [comment]
Sugiro mudar de 

caInfo: string caminho absoluto do arquivo do certificado

Para 

companyName: string nome da empresa
privateKey: string chave privada PEM
publicKey: string chave pública PEM
cert: string  certificado PEM (chave publica + cadeia )
caInfo: string path para cacerts do sistema operacional
validFrom: \DateTime data de início da validade do certificado
validTo: \DateTime data de término da validade do certificado

**Comment by tonicospinelli** [comment]
@robmachado editei conforme sugeriu, faz bastante sentido!

**Comment by robmachado** [comment]
Vamos falar de dados brutos dos certificados:
1 - openssl_pkcs12_read() --> fornece as chaves (privada e publica) apenas isso
2 - openssl_x509_parse(openssl_x509_read($pubKey)) --> retorna arrays com validFrom,  validTo companyName

Falta uma informação crucial CNPJ do certificado, para isso só usando classes como a ASN que faz a leitura dos OID (conjunto extenso de dados binários inseridos na chave)

**Comment by tonicospinelli** [comment]
@robmachado adicionei o `companyIdentifier` para representar o CNPJ da empresa no certificado
