### ISSUE TITLE
classe para ler certificado

### ISSUE THREAD

**Issue by tonicospinelli** [nfephp-org/sped-common#42]
devemos criar uma classe para fazer a leitura do arquivo de certificado do tipo A1

talvez nesse momento não precise criar uma interface, a não ser que tenhamos outros tipos de leitores de certificado

comportamento esperado:
- **load($content, $password = '')**: *Certificate* após ler o certificado deve retornar o objeto relacionado - depende da issue #41
 - em caso de sucesso na leitura do certificado deverá retornar uma instancia da classe `Certificate`
 - em caso de falha na leitura, deverá lançar uma exception `UnexpectedContentException::cannotRead`

**Comment by lpj145** [comment]
@tonicospinelli defina um nome para a classe, CertificateReader

**Comment by tonicospinelli** [comment]
@lpj145 seguindo o namespace, podemos ter `NFePHP\Common\Certificate\Reader`

**Comment by Ferreiramg** [comment]
Me questiono do porque o load deveria retornar algo!

**Comment by tonicospinelli** [comment]
conforme acordamos não será preciso uma classe separada para fazer isso
