### ISSUE TITLE
Definições ClientRequest e ServicesRequest Interface

### ISSUE THREAD

**Issue by Ferreiramg** [nfephp-org/sped-common#54]
Client abstrato responsável em enviar a Requisição, recebe um Service Interface que implementa métodos necessários para requisição do Serviço . 
Proposta. 

**Client**
- send(ServiceRequest $service): Monta a requisição, envia e retorna resposta da requisição.

**ServiceRequest**
- withUri($uri): recebe url do serviço
- withHeader($header): recebe headers do serviço
- withBody($body):recebe body context do serviço

**Comment by robmachado** [comment]
Já foi feita a Interface para SOAP e montado os objetos SOAPCURL e SOAPNATIVE, estou fazendo os testes operacionais com essas classes no sped-nfse e no sped-nfe (branch v5.0).
Infelizmente não são tão simples como se poderia pensar em virtude de diferenças dos webservices.
