### ISSUE TITLE
A saída verbosa do curl deve ser parametrizada

### ISSUE THREAD

**Issue by Gleidson2012** [nfephp-org/sped-common#76]
Ao definir `true` na opção `CURLOPT_VERBOSE` a saída verbosa é direcionada para a `stderr`.
Caso você possua programas/testes que geram saída formatada, haverá mistura entre a `stdout` e `stderr`.

```php
// fully-qualified name: \NFePHP\Common\Soap\CurlSoap
curl_setopt($oCurl, CURLOPT_VERBOSE, 1);
```

**Comment by robmachado** [comment]
Realmente ... podemos capturar então essa saída do stderr e direcionar para um LOG estou pensando em faze-lo usando o Monolog

**Comment by Gleidson2012** [comment]
Numa análise do código atual, contrapondo a sua sugestão de usar o Monolog, acredito ser mais efetivo a definição de uma configuração condicionando o comportamento. Essa definição opcional seria `curlStderrStream`, sendo o nome do arquivo a ser usado como STDERR.

```php
// fully-qualified name: \NFePHP\Common\Soap\CurlSoap:~270

if (!is_null($this->curlStderrStream)){
    if (is_writable($this->curlStderrStream)) {
        curl_setopt($oCurl, CURLOPT_VERBOSE, 1);
        curl_setopt($oCurl, CURLOPT_STDERR, fopen($this->curlStderrStream, 'w'));
    } else {
        throw new Exception\RuntimeException("O Arquivo definido como CURLOPT_STDERR não tem permissão de escrita ou não existe ({$this->curlStderrStream})");
    }
}
```

O que acha?
