### ISSUE TITLE
Incluir remoção do namespace cte

### ISSUE THREAD

**Issue by Gleidson2012** [nfephp-org/sped-common#84]
Implementar remoção do namespace {http://www.portalfiscal.inf.br/nfe} das mensagens de erro na validação do XML - \NFePHP\Common\Dom\ValidXsd::validar()

**Comment by robmachado** [comment]
Eu não entendi sua colocação ??? Qual é o problema encontrado e como ocorre ??

**Comment by Gleidson2012** [comment]
Então @robmachado 

no método ```php \NFePHP\Common\Dom\ValidXsd::zTranslateError()``` é feita uma substituição de             `"{http://www.portalfiscal.inf.br/nfe}"` por string vazia, porém ao usar com CT-e ele não remove.

**Comment by robmachado** [comment]
Bom na nova versão v5.0 não mais serão traduzidas as mensagens !! Estou terminando de acertar as mudanças em sped-common para alterar a partir dai as APIs dependentes desse pacote. Ai não é mais necessário remover o namespace

**Comment by Gleidson2012** [comment]
Entendi. Perfeito! 
Provável que eu implemente essa semana. Daí faço pull request

**Comment by robmachado** [comment]
OK ... mas lembre-se que neste semestre ainda haverão atualizações relativamente GRANDES em vários repositórios.

**Comment by Gleidson2012** [comment]
OK! Irei planejar as migrações internas. =]

**Comment by robmachado** [comment]
As versões atuais ainda permanecerão disponíveis em outras branchs e nas tags mas não mais serão mantidas ou atualizadas por mim ou pelos maiores colaboradores.  Então em principio dá para planejar as alterações (que em alguns casos são muitas) em um ambiente de desenvolvimento antes de migrar em produção.

**Comment by Gleidson2012** [comment]
Certo!

**Comment by robmachado** [comment]
É só acompanhar o desenvolvimento, muitas coisas ainda não estão funcionais e ainda serão alteradas antes que entre o primeiro RELEASE dessas novas versões
